#setup eureka client
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 172.18.0.2
    non-secure-port: 8761    
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://172.18.0.2:8761/eureka
