#setup eureka client
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost    
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
